CREATE TABLE demo_training_sessions (
    id VARCHAR(36) PRIMARY KEY,
    balance BIGINT NOT NULL CHECK (balance >= 0),
    lifetime_earned BIGINT NOT NULL DEFAULT 0,
    lifetime_used BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_training_session_created ON demo_training_sessions(created_at);
CREATE INDEX ix_training_session_expiry ON demo_training_sessions(expires_at);
CREATE TABLE demo_training_capacity (id INTEGER PRIMARY KEY);
INSERT INTO demo_training_capacity(id) VALUES (1);
CREATE TABLE demo_training_predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL REFERENCES demo_training_sessions(id),
    event_id BIGINT NOT NULL REFERENCES arena_events(id),
    market_id BIGINT NOT NULL REFERENCES arena_markets(id),
    option_id BIGINT NOT NULL REFERENCES arena_market_options(id),
    stake_points INTEGER NOT NULL CHECK (stake_points > 0),
    multiplier NUMERIC(8,3) NOT NULL CHECK (multiplier > 0),
    model_version VARCHAR(50),
    potential_points INTEGER NOT NULL,
    rewarded_points INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    idempotency_key VARCHAR(80) NOT NULL,
    placed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE,
    UNIQUE(session_id, idempotency_key)
);
CREATE INDEX ix_training_event_status ON demo_training_predictions(event_id, status);
CREATE INDEX ix_training_session_time ON demo_training_predictions(session_id, placed_at DESC);
CREATE TABLE demo_training_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL REFERENCES demo_training_sessions(id),
    type VARCHAR(32) NOT NULL,
    amount BIGINT NOT NULL,
    balance_after BIGINT NOT NULL CHECK (balance_after >= 0),
    idempotency_key VARCHAR(120) NOT NULL,
    description VARCHAR(300) NOT NULL,
    reference_id VARCHAR(40),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(session_id, idempotency_key)
);
CREATE INDEX ix_training_ledger_session ON demo_training_ledger(session_id, created_at DESC);
