-- ArenaPredict schema baseline. PostgreSQL and H2 compatible by design.
-- Legacy tables remain only for safe migration of the original portfolio project.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    code VARCHAR(3) NOT NULL UNIQUE,
    flag_emoji VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    home_team_id BIGINT NOT NULL,
    away_team_id BIGINT NOT NULL,
    external_id VARCHAR(255) UNIQUE,
    starts_at TIMESTAMP NOT NULL,
    phase VARCHAR(40) NOT NULL,
    match_group VARCHAR(255),
    venue VARCHAR(255),
    status VARCHAR(40) NOT NULL,
    home_score INTEGER,
    away_score INTEGER
);

CREATE TABLE IF NOT EXISTS pools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1200),
    entry_fee NUMERIC(12,2) NOT NULL,
    status VARCHAR(40) NOT NULL,
    invite_code VARCHAR(12) NOT NULL UNIQUE,
    created_by_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pool_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pool_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(pool_id, user_id)
);

CREATE TABLE IF NOT EXISTS predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pool_id BIGINT NOT NULL,
    match_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    home_score INTEGER NOT NULL,
    away_score INTEGER NOT NULL,
    points INTEGER NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(pool_id, match_id, user_id)
);

CREATE TABLE IF NOT EXISTS rankings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pool_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    points INTEGER NOT NULL,
    hits INTEGER NOT NULL,
    goal_difference INTEGER NOT NULL,
    UNIQUE(pool_id, user_id)
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pool_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(40) NOT NULL,
    provider_payment_id VARCHAR(255),
    qr_code_base64 VARCHAR(4000),
    qr_code VARCHAR(4000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    approved_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS arena_sports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(24) NOT NULL,
    icon VARCHAR(80),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS arena_championships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(120) NOT NULL,
    season VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    image_url VARCHAR(300),
    starts_at TIMESTAMP WITH TIME ZONE,
    ends_at TIMESTAMP WITH TIME ZONE,
    UNIQUE(sport_id, slug, season)
);

CREATE TABLE IF NOT EXISTS arena_competitors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    code VARCHAR(30) NOT NULL,
    image_url VARCHAR(300),
    country VARCHAR(80),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE(sport_id, code)
);

CREATE TABLE IF NOT EXISTS arena_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_key VARCHAR(100) NOT NULL UNIQUE,
    championship_id BIGINT NOT NULL,
    home_competitor_id BIGINT,
    away_competitor_id BIGINT,
    title VARCHAR(180) NOT NULL,
    stage VARCHAR(100),
    venue VARCHAR(160),
    broadcast VARCHAR(160),
    image_url VARCHAR(300),
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    prediction_closes_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(32) NOT NULL,
    format VARCHAR(20) NOT NULL,
    best_of INTEGER NOT NULL DEFAULT 1,
    home_score INTEGER,
    away_score INTEGER,
    clock VARCHAR(80),
    period VARCHAR(80),
    live_data VARCHAR(4000),
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    demo BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS arena_markets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    code VARCHAR(80) NOT NULL,
    name VARCHAR(140) NOT NULL,
    status VARCHAR(20) NOT NULL,
    minimum_points INTEGER NOT NULL DEFAULT 10,
    result_option_key VARCHAR(80),
    settled_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    UNIQUE(event_id, code)
);

CREATE TABLE IF NOT EXISTS arena_market_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market_id BIGINT NOT NULL,
    option_key VARCHAR(80) NOT NULL,
    label VARCHAR(140) NOT NULL,
    multiplier NUMERIC(8,3) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE(market_id, option_key)
);

CREATE TABLE IF NOT EXISTS arena_point_wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    balance BIGINT NOT NULL DEFAULT 0,
    lifetime_earned BIGINT NOT NULL DEFAULT 0,
    lifetime_used BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS arena_point_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    amount BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL UNIQUE,
    reference_type VARCHAR(60),
    reference_id VARCHAR(80),
    description VARCHAR(220) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS arena_pools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    sport_id BIGINT,
    championship_id BIGINT,
    owner_id BIGINT NOT NULL,
    invite_code VARCHAR(16) NOT NULL UNIQUE,
    public_pool BOOLEAN NOT NULL DEFAULT FALSE,
    max_participants INTEGER NOT NULL DEFAULT 100,
    virtual_prize_points INTEGER NOT NULL DEFAULT 0,
    rules VARCHAR(1200) NOT NULL,
    status VARCHAR(20) NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE,
    ends_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS arena_pool_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pool_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    moderator BOOLEAN NOT NULL DEFAULT FALSE,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(pool_id, user_id)
);

CREATE TABLE IF NOT EXISTS arena_predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    market_id BIGINT NOT NULL,
    option_id BIGINT NOT NULL,
    pool_id BIGINT,
    stake_points INTEGER NOT NULL,
    multiplier NUMERIC(8,3) NOT NULL,
    potential_points INTEGER NOT NULL,
    rewarded_points INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL UNIQUE,
    placed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS arena_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(40) NOT NULL,
    title VARCHAR(140) NOT NULL,
    message VARCHAR(600) NOT NULL,
    target_url VARCHAR(240),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    read_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_arena_events_status_starts ON arena_events(status, starts_at);
CREATE INDEX IF NOT EXISTS idx_arena_markets_event_status ON arena_markets(event_id, status);
CREATE INDEX IF NOT EXISTS idx_arena_predictions_user_status ON arena_predictions(user_id, status);
CREATE INDEX IF NOT EXISTS idx_arena_predictions_market_status ON arena_predictions(market_id, status);
CREATE INDEX IF NOT EXISTS idx_arena_point_transactions_wallet_created ON arena_point_transactions(wallet_id, created_at);
CREATE INDEX IF NOT EXISTS idx_arena_notifications_user_read ON arena_notifications(user_id, read_at);
