CREATE TABLE arena_player_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    avatar_url VARCHAR(300),
    bio VARCHAR(500),
    favorite_sports VARCHAR(600),
    theme VARCHAR(20) NOT NULL DEFAULT 'dark',
    language VARCHAR(12) NOT NULL DEFAULT 'pt-BR',
    notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    public_profile BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE arena_achievement_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500) NOT NULL,
    rarity VARCHAR(30) NOT NULL,
    rule VARCHAR(40) NOT NULL,
    target INTEGER NOT NULL CHECK (target > 0),
    points_reward INTEGER NOT NULL CHECK (points_reward >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE arena_user_achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    achievement_id BIGINT NOT NULL REFERENCES arena_achievement_definitions(id),
    progress INTEGER NOT NULL DEFAULT 0 CHECK (progress >= 0),
    unlocked_at TIMESTAMP WITH TIME ZONE,
    reward_granted BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE(user_id, achievement_id)
);

CREATE TABLE arena_challenge_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500) NOT NULL,
    metric VARCHAR(40) NOT NULL,
    target INTEGER NOT NULL CHECK (target > 0),
    reward_points INTEGER NOT NULL CHECK (reward_points >= 0),
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK (expires_at > starts_at)
);

CREATE TABLE arena_user_challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    challenge_id BIGINT NOT NULL REFERENCES arena_challenge_definitions(id),
    progress INTEGER NOT NULL DEFAULT 0 CHECK (progress >= 0),
    completed_at TIMESTAMP WITH TIME ZONE,
    reward_granted BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE(user_id, challenge_id)
);

CREATE TABLE arena_community_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL REFERENCES users(id),
    content VARCHAR(600) NOT NULL,
    topic VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL,
    source_key VARCHAR(80) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE arena_community_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES arena_community_posts(id),
    author_id BIGINT NOT NULL REFERENCES users(id),
    content VARCHAR(600) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE arena_community_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES arena_community_posts(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(post_id, user_id)
);

CREATE TABLE arena_community_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES arena_community_posts(id),
    reporter_id BIGINT NOT NULL REFERENCES users(id),
    reason VARCHAR(300) NOT NULL,
    status VARCHAR(20) NOT NULL,
    moderator_note VARCHAR(500),
    moderated_by_id BIGINT REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    UNIQUE(post_id, reporter_id)
);

CREATE INDEX idx_arena_user_achievements_user ON arena_user_achievements(user_id, unlocked_at);
CREATE INDEX idx_arena_user_challenges_user ON arena_user_challenges(user_id, completed_at);
CREATE INDEX idx_arena_community_posts_feed ON arena_community_posts(status, created_at);
CREATE INDEX idx_arena_community_comments_post ON arena_community_comments(post_id, status, created_at);
CREATE INDEX idx_arena_community_likes_post ON arena_community_likes(post_id);
CREATE INDEX idx_arena_community_reports_status ON arena_community_reports(status, created_at);
