-- Append-only administrative audit trail. Application code only inserts into
-- this table; immutable actor snapshots keep old entries useful after profile
-- changes while actor_id retains relational traceability when available.
CREATE TABLE arena_admin_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT,
    actor_name VARCHAR(120) NOT NULL,
    actor_role VARCHAR(40) NOT NULL,
    action VARCHAR(80) NOT NULL,
    resource_type VARCHAR(60) NOT NULL,
    resource_id VARCHAR(80),
    status VARCHAR(20) NOT NULL,
    summary VARCHAR(500),
    correlation_id VARCHAR(80),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_arena_admin_audit_actor FOREIGN KEY (actor_id) REFERENCES users(id)
);

CREATE INDEX idx_arena_admin_audit_created
    ON arena_admin_audit_events(created_at);

CREATE INDEX idx_arena_admin_audit_resource
    ON arena_admin_audit_events(resource_type, resource_id);

CREATE INDEX idx_arena_admin_audit_actor
    ON arena_admin_audit_events(actor_id, created_at);

-- Refunds return previously debited points and are not XP/earnings. Rebuild the
-- denormalized counter from the immutable ledger so existing demo databases are
-- corrected as part of the same versioned migration.
UPDATE arena_point_wallets
SET lifetime_earned = COALESCE((
    SELECT SUM(entry.amount)
    FROM arena_point_transactions entry
    WHERE entry.wallet_id = arena_point_wallets.id
      AND entry.amount > 0
      AND entry.type <> 'REFUND'
), 0);
